title: <p align="center"> Vinoth Nanda Kumaran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Vinoth Resume - Final Updated.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vinothnk/">LinkedIn</a> |
  <a href="https://github.com/vinothnk">GitHub</a>
  </p>
  
  <p align="justify">
  I'm Vinoth, a driven professional with 12+ years of experience in logistics, warehouse management, 
  and business operations, now pursuing a degree in Business Analytics to bridge the gap between data and decision-making. 
  With a strong foundation in Python, SQL, and data visualization tools like Tableau and Power BI.
  I’m passionate about leveraging data to optimize processes and drive business growth. 
  I’m also a certified data analyst and a junior data engineer, continually expanding my technical skills and working on real-world projects. 
  Let’s collaborate to turn data into actionable insights!
  <br><br>
  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-3YS8RW7EWH # Google Analytics tracking ID
