title: <p align="center"> Vinoth Nanda Kumaran </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vinothnk/">LinkedIn</a> |
  <a href="https://github.com/vinothnk">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-3YS8RW7EWH # Google Analytics tracking ID
